//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonbok.TelefonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TelefonService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TelefonService.IKontaktService")]
    public interface IKontaktService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/GetData", ReplyAction="http://tempuri.org/IKontaktService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IKontaktService/GetDataUsingDataContractResponse")]
        Telefonbok.TelefonService.CompositeType GetDataUsingDataContract(Telefonbok.TelefonService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/HämtaAllaKontakter", ReplyAction="http://tempuri.org/IKontaktService/HämtaAllaKontakterResponse")]
        System.Xml.Linq.XElement HämtaAllaKontakter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/LäggTillKontakt", ReplyAction="http://tempuri.org/IKontaktService/LäggTillKontaktResponse")]
        void LäggTillKontakt(System.Xml.Linq.XElement kontakt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/TaBortKontakt", ReplyAction="http://tempuri.org/IKontaktService/TaBortKontaktResponse")]
        void TaBortKontakt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/ÄndraKontakt", ReplyAction="http://tempuri.org/IKontaktService/ÄndraKontaktResponse")]
        void ÄndraKontakt(System.Xml.Linq.XElement ändradKontakt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/SökKontakter", ReplyAction="http://tempuri.org/IKontaktService/SökKontakterResponse")]
        System.Xml.Linq.XElement SökKontakter(System.Xml.Linq.XElement kriterier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKontaktServiceChannel : Telefonbok.TelefonService.IKontaktService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KontaktServiceClient : System.ServiceModel.ClientBase<Telefonbok.TelefonService.IKontaktService>, Telefonbok.TelefonService.IKontaktService {
        
        public KontaktServiceClient() {
        }
        
        public KontaktServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Telefonbok.TelefonService.CompositeType GetDataUsingDataContract(Telefonbok.TelefonService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Xml.Linq.XElement HämtaAllaKontakter() {
            return base.Channel.HämtaAllaKontakter();
        }
        
        public void LäggTillKontakt(System.Xml.Linq.XElement kontakt) {
            base.Channel.LäggTillKontakt(kontakt);
        }
        
        public void TaBortKontakt(int id) {
            base.Channel.TaBortKontakt(id);
        }
        
        public void ÄndraKontakt(System.Xml.Linq.XElement ändradKontakt) {
            base.Channel.ÄndraKontakt(ändradKontakt);
        }
        
        public System.Xml.Linq.XElement SökKontakter(System.Xml.Linq.XElement kriterier) {
            return base.Channel.SökKontakter(kriterier);
        }
    }
}
